# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
 
# Require YAML module
require 'yaml'
 
# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

# Disabled vbguest additions
config.vm.box_check_update = false
config.vbguest.auto_update = false

    # Iterate through entries in YAML file
    servers.each do |server|
        config.vm.define server['name'] do |srv|
            srv.vm.box = server['box']
            srv.vm.hostname = server ['hostname']
            srv.vm.network "private_network", ip: server["ip"]
            srv.vm.provider :virtualbox do |vb|
            vb.name = server["name"]
            vb.memory = server["ram"]
            vb.cpus = server['vcpu']

            config.vm.provision :shell, path: server["provision"] if server["provision"]
            
end
end
end
end
