# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 2.2.14"
VAGRANTFILE_API_VERSION = "2"
 
# Require YAML module
require 'yaml'
 
# Read YAML file with box details
hosts = YAML.load_file('vagrant_hosts.yaml')

# Disabled vbguest additions
#config.vm.box_check_update = false
#config.vbguest.auto_update = false

# Create and configure the VMs
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

# Disabled vbguest additions
config.vm.box_check_update = false
config.vbguest.auto_update = false

# Iterate through entries in YAML file
hosts.each do |host|
  config.vm.define host['name'] do |node|
    node.vm.box = host['box']
    node.vm.hostname = host['hostname']
    node.vm.network :private_network, ip: host['ip']
    
    node.vm.provider :virtualbox do |vb|
      vb.name = host['name']
      vb.memory = host['ram']
      vb.cpus = host['vcpu']
end
    node.vm.provision :shell do |sh|
      sh.path = host['provision']

#config.vm.provision "shell", inline: "echo VM has been provisioned successfully"
#config.vm.provision :shell, run: 'always', path: host['provision'] if host['provision']

end # config.vm.provider 'virtualbox'
end # config.vm.define
end # config.vm.provision
end # Vagrant.configure
